# fly.toml app configuration file generated for pdfai-summary on 2023-07-16T12:11:27+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdfai-summary"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
